[package]
name = "patbot"
version = "0.1.0"
edition = "2021"

[dependencies]
dotenv = "0.15"
once_cell = "1.19"
poise = "0.6"
rand = "0.8"
reqwest = "0.11"
serde = { version = "1", features = ["derive"] }
tokio = { version = "1.35", features = ["macros", "rt-multi-thread", "rt"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter"] }
